### ISSUE TITLE
.on('listening' function () - SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by JessWallace94** [JessWallace94/gulpTest#1]
```
 .on('listening' function () {
                    ^^^^^^^^
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```

**Comment by JessWallace94** [comment]
Missing ',' after the  .on('listening' function ()
